import { type Family, type Role, FAMILIES } from "./families";

export interface Compound {
  id: string;
  name: string;
  commonName: string;
  family: Family;
  role: Role;
  cas: string;
  description: string;
  classicPairings: string[];
  ifraCategoryFlags: string[];
  defaultPercent: number;
  volatility: number;
  position: { tier: 0 | 1 | 2; slot: number };
  hexColor: string;
}

export const COMPOUNDS: Compound[] = [
  {
    id: "bergamote-italian",
    name: "Bergamote (Italie)",
    commonName: "Bergamot",
    family: "citrus",
    role: "top",
    cas: "8007-75-8",
    description:
      "Cool, sun-bleached citrus with a green-floral twist. The opening of nearly every chypre worth remembering. Sharper than orange, less sour than lemon.",
    classicPairings: ["rose-de-mai", "jasmin-sambac", "vetiver-haiti", "labdanum"],
    ifraCategoryFlags: ["Bergapten content — phototoxicity limits in leave-on (Cat 1–4)"],
    defaultPercent: 5,
    volatility: 0.95,
    position: { tier: 0, slot: 0 },
    hexColor: "#E8C84A",
  },
  {
    id: "citron-sicilian",
    name: "Citron (Sicile)",
    commonName: "Lemon",
    family: "citrus",
    role: "top",
    cas: "8008-56-8",
    description:
      "The bright knife. Sharper, more linear than bergamot, less sweet than orange. Used to cut through florals and add daylight to a heavy heart.",
    classicPairings: ["neroli-tunisia", "thé-vert", "iso-e-super", "cedre-virginia"],
    ifraCategoryFlags: ["Citral content limits in leave-on"],
    defaultPercent: 4,
    volatility: 0.98,
    position: { tier: 0, slot: 1 },
    hexColor: "#F4DA62",
  },
  {
    id: "orange-douce",
    name: "Orange Douce (Brésil)",
    commonName: "Sweet Orange",
    family: "citrus",
    role: "top",
    cas: "8008-57-9",
    description:
      "Round, sunny, immediately familiar — which is the problem. On its own it reads as cleaning product; with neroli or jasmine it becomes a memory of summer.",
    classicPairings: ["neroli-tunisia", "fleur-d-oranger", "vanille-bourbon", "cardamome"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.96,
    position: { tier: 0, slot: 2 },
    hexColor: "#F0A04A",
  },
  {
    id: "mandarine-rouge",
    name: "Mandarine Rouge",
    commonName: "Red Mandarin",
    family: "citrus",
    role: "top",
    cas: "8008-31-9",
    description:
      "The most edible of the citruses. Honeyed, slightly indolic at the end. Pairs with gourmands without becoming candy.",
    classicPairings: ["feve-tonka", "iris-orris", "praline", "magnolia"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.94,
    position: { tier: 0, slot: 3 },
    hexColor: "#E68A33",
  },
  {
    id: "pamplemousse-rose",
    name: "Pamplemousse Rose",
    commonName: "Pink Grapefruit",
    family: "citrus",
    role: "top",
    cas: "8016-20-4",
    description:
      'Bitter and slightly sulfurous in the natural — that thiol note is what makes it modern. Lifts aquatics and reads "clean" without going to laundry.',
    classicPairings: ["calone", "iso-e-super", "cedre-atlas", "helional"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.97,
    position: { tier: 0, slot: 4 },
    hexColor: "#E89B85",
  },
  {
    id: "lime-persian",
    name: "Lime (Perse)",
    commonName: "Lime",
    family: "citrus",
    role: "top",
    cas: "8008-26-2",
    description:
      "Greener and more piercing than lemon. There is a reason almost every cologne fougère starts with this material — it forces the rest of the structure to keep up.",
    classicPairings: ["galbanum", "menthe-poivrée", "vetiver-haiti", "iso-e-super"],
    ifraCategoryFlags: ["Phototoxicity limits in leave-on"],
    defaultPercent: 3,
    volatility: 0.99,
    position: { tier: 0, slot: 5 },
    hexColor: "#A8C04A",
  },
  {
    id: "neroli-tunisia",
    name: "Néroli (Tunisie)",
    commonName: "Neroli",
    family: "citrus",
    role: "top",
    cas: "8016-38-4",
    description:
      "Distilled bitter orange flower — the cleanest of the white florals. Sits at the boundary of citrus and floral; can be deployed as either. Beloved of perfumers who want elegance without weight.",
    classicPairings: ["bergamote-italian", "rose-de-mai", "iris-orris", "musc-blanc"],
    ifraCategoryFlags: [],
    defaultPercent: 5,
    volatility: 0.88,
    position: { tier: 0, slot: 6 },
    hexColor: "#F4E1B8",
  },
  {
    id: "yuzu",
    name: "Yuzu (Japon)",
    commonName: "Yuzu",
    family: "citrus",
    role: "top",
    cas: "438540-39-3",
    description:
      "A citrus that reads as a citrus the way a haiku reads as a poem — half of what you expect, twice as precise. Floral, slightly resinous, distinctly Japanese.",
    classicPairings: ["thé-vert", "magnolia", "cedre-virginia", "feuille-de-tomate"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.93,
    position: { tier: 0, slot: 7 },
    hexColor: "#D9D26B",
  },
  {
    id: "galbanum",
    name: "Galbanum (Iran)",
    commonName: "Galbanum",
    family: "green",
    role: "top",
    cas: "8023-91-4",
    description:
      "The greenest material in the perfumer's palette. Crushed-stem, almost sour, ferocious at full strength. The opening of Chamade and No. 19. Uncompromising — perfumers who use it know exactly what they are doing.",
    classicPairings: ["rose-de-mai", "iris-orris", "mousse-de-chêne", "vetiver-haiti"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.85,
    position: { tier: 0, slot: 8 },
    hexColor: "#7A9657",
  },
  {
    id: "feuille-de-violette",
    name: "Feuille de Violette",
    commonName: "Violet Leaf Absolute",
    family: "green",
    role: "top",
    cas: "8024-08-6",
    description:
      "Cucumber, wet metal, the inside of an envelope. Reads green but with a watery quality that bridges aquatics and florals. The rare green that can sit at the heart.",
    classicPairings: ["violette", "iris-orris", "feve-tonka", "iso-e-super"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.82,
    position: { tier: 0, slot: 9 },
    hexColor: "#8FA47A",
  },
  {
    id: "feuille-de-tomate",
    name: "Feuille de Tomate",
    commonName: "Tomato Leaf",
    family: "green",
    role: "top",
    cas: "93685-94-0",
    description:
      "Sticky, herbal, slightly bitter — the smell of a greenhouse in July. Brings vegetal credibility to fig and aquatic accords. Use 0.5 to 1% or it dominates.",
    classicPairings: ["magnolia", "cedre-virginia", "galbanum", "iso-e-super"],
    ifraCategoryFlags: [],
    defaultPercent: 1,
    volatility: 0.84,
    position: { tier: 0, slot: 10 },
    hexColor: "#7E9968",
  },
  {
    id: "thé-vert",
    name: "Thé Vert (Sencha)",
    commonName: "Green Tea Accord",
    family: "green",
    role: "top",
    cas: "84650-60-2",
    description:
      "A constructed accord — there is no commercial tea distillate that smells like brewed tea. Mild, slightly hay-like, transparent. Used to suggest restraint.",
    classicPairings: ["yuzu", "iris-orris", "magnolia", "hedione"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.86,
    position: { tier: 0, slot: 11 },
    hexColor: "#A0B387",
  },
  {
    id: "mate",
    name: "Maté Absolu",
    commonName: "Yerba Mate",
    family: "green",
    role: "top",
    cas: "68916-96-1",
    description:
      "Dry hay, tobacco, and cured leaf. More masculine than green tea, less heavy than tobacco absolute. A modern green for compositions that want grain rather than grass.",
    classicPairings: ["feve-tonka", "cedre-virginia", "iso-e-super", "labdanum"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.78,
    position: { tier: 0, slot: 12 },
    hexColor: "#8B9870",
  },
  {
    id: "calone",
    name: "Calone 1951",
    commonName: "Calone",
    family: "aquatic",
    role: "top",
    cas: "28940-11-6",
    description:
      "The molecule that built the entire 1990s. Watermelon-rind, ozone, sea breeze. Banned from chypres on principle. Used at 0.1% it adds light; at 1% it eats everything.",
    classicPairings: ["helional", "pamplemousse-rose", "iso-e-super", "florhydral"],
    ifraCategoryFlags: [],
    defaultPercent: 1,
    volatility: 0.92,
    position: { tier: 0, slot: 13 },
    hexColor: "#7FA8B8",
  },
  {
    id: "helional",
    name: "Helional",
    commonName: "Helional",
    family: "aquatic",
    role: "top",
    cas: "1205-17-0",
    description:
      "A softer aquatic than calone — more skin, less fishbowl. Floralizes water notes. Underused; sits beautifully under iris and magnolia.",
    classicPairings: ["magnolia", "iris-orris", "iso-e-super", "calone"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.88,
    position: { tier: 0, slot: 14 },
    hexColor: "#9AB8C0",
  },
  {
    id: "florhydral",
    name: "Florhydral",
    commonName: "Florhydral",
    family: "aquatic",
    role: "top",
    cas: "125109-85-5",
    description:
      "Lily-of-the-valley, freshly cut, with a saline edge. Bridges aquatic and floral cleanly. Modern, almost transparent.",
    classicPairings: ["muguet-hedione", "magnolia", "helional", "iso-e-super"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.9,
    position: { tier: 0, slot: 15 },
    hexColor: "#A8C8D0",
  },

  {
    id: "rose-de-mai",
    name: "Rose de Mai",
    commonName: "May Rose Absolute",
    family: "floral",
    role: "heart",
    cas: "8007-01-0",
    description:
      "The Grasse rose, harvested for three weeks in May. Powdery, honeyed, slightly green — entirely unlike supermarket roses. Expensive and irreplaceable.",
    classicPairings: ["jasmin-sambac", "patchouli", "oud", "bergamote-italian"],
    ifraCategoryFlags: [],
    defaultPercent: 8,
    volatility: 0.55,
    position: { tier: 1, slot: 0 },
    hexColor: "#E89BB0",
  },
  {
    id: "rose-damascena",
    name: "Rose Damascena",
    commonName: "Damascus Rose",
    family: "floral",
    role: "heart",
    cas: "90106-38-0",
    description:
      "The Bulgarian and Turkish rose. Wine-dark, more honeyed than Grasse, with a pronounced fruity edge from beta-damascenone. The rose of oriental compositions.",
    classicPairings: ["oud", "safran", "patchouli", "cardamome"],
    ifraCategoryFlags: [],
    defaultPercent: 7,
    volatility: 0.55,
    position: { tier: 1, slot: 1 },
    hexColor: "#C26B7A",
  },
  {
    id: "jasmin-sambac",
    name: "Jasmin Sambac",
    commonName: "Sambac Jasmine",
    family: "floral",
    role: "heart",
    cas: "91770-14-8",
    description:
      "The night-blooming Indian jasmine. Tea-leaf and gardenia tones, less indolic than grandiflorum. Reads modern; sits beautifully under iris and pear.",
    classicPairings: ["rose-de-mai", "tubéreuse", "thé-vert", "magnolia"],
    ifraCategoryFlags: [],
    defaultPercent: 6,
    volatility: 0.5,
    position: { tier: 1, slot: 2 },
    hexColor: "#F4E1C8",
  },
  {
    id: "jasmin-grandiflorum",
    name: "Jasmin Grandiflorum",
    commonName: "Jasmine Absolute",
    family: "floral",
    role: "heart",
    cas: "8022-96-6",
    description:
      "The Grasse jasmine. Heavy with indole — almost fecal at full concentration, magnificently floral when diluted. Half the heart of every great chypre.",
    classicPairings: ["rose-de-mai", "mousse-de-chêne", "patchouli", "civette"],
    ifraCategoryFlags: [],
    defaultPercent: 8,
    volatility: 0.48,
    position: { tier: 1, slot: 3 },
    hexColor: "#F0D89A",
  },
  {
    id: "ylang-ylang",
    name: "Ylang-Ylang Extra",
    commonName: "Ylang-Ylang",
    family: "floral",
    role: "heart",
    cas: "8006-81-3",
    description:
      "Custardy, narcotic, slightly banana — the flower that smells like dessert. Use the Extra grade for fine fragrance; Premier and First grades read more cosmetic.",
    classicPairings: ["santal-mysore", "vanille-bourbon", "jasmin-grandiflorum", "feve-tonka"],
    ifraCategoryFlags: ["Allergen labeling required (linalool, isoeugenol)"],
    defaultPercent: 6,
    volatility: 0.5,
    position: { tier: 1, slot: 4 },
    hexColor: "#F4D89C",
  },
  {
    id: "fleur-d-oranger",
    name: "Fleur d'Oranger",
    commonName: "Orange Blossom Absolute",
    family: "floral",
    role: "heart",
    cas: "8016-38-4",
    description:
      "The absolute, not the distillate. Honey, indole, a little leather. Where neroli is daylight, fleur d'oranger is the same flower at midnight.",
    classicPairings: ["jasmin-grandiflorum", "cedre-atlas", "vanille-bourbon", "orange-douce"],
    ifraCategoryFlags: [],
    defaultPercent: 7,
    volatility: 0.5,
    position: { tier: 1, slot: 5 },
    hexColor: "#F4E8C0",
  },
  {
    id: "tubéreuse",
    name: "Tubéreuse",
    commonName: "Tuberose Absolute",
    family: "floral",
    role: "heart",
    cas: "8024-05-3",
    description:
      "The most polarizing white floral. Coconut, methyl benzoate, rubber — and underneath it, a softness almost obscene. Polarizing on purpose. The flower of Fracas.",
    classicPairings: ["ylang-ylang", "jasmin-sambac", "santal-mysore", "gardénia"],
    ifraCategoryFlags: [],
    defaultPercent: 5,
    volatility: 0.42,
    position: { tier: 1, slot: 6 },
    hexColor: "#F4E0E5",
  },
  {
    id: "magnolia",
    name: "Magnolia",
    commonName: "Magnolia",
    family: "floral",
    role: "heart",
    cas: "68917-09-9",
    description:
      "Lemony floral, almost transparent. The most modern of the white florals — clean lines, no indole. Reads luxurious without weight.",
    classicPairings: ["yuzu", "helional", "iso-e-super", "feuille-de-tomate"],
    ifraCategoryFlags: [],
    defaultPercent: 5,
    volatility: 0.6,
    position: { tier: 1, slot: 7 },
    hexColor: "#F4E8B8",
  },
  {
    id: "iris-orris",
    name: "Iris (Orris Butter)",
    commonName: "Iris / Orris",
    family: "floral",
    role: "heart",
    cas: "8002-73-1",
    description:
      "The most expensive material in mainstream perfumery — three years of root drying for an oil that smells of cold violets, suede, and old paper. Restraint built into the molecule.",
    classicPairings: ["violette", "feve-tonka", "santal-mysore", "cedre-virginia"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.4,
    position: { tier: 1, slot: 8 },
    hexColor: "#D9CFB8",
  },
  {
    id: "geranium-bourbon",
    name: "Géranium Bourbon",
    commonName: "Bourbon Geranium",
    family: "floral",
    role: "heart",
    cas: "8000-46-2",
    description:
      "Half rose, half mint, half something metallic. The connective tissue of fougères and chypres. Cooler and more masculine than the rose it imitates.",
    classicPairings: ["rose-de-mai", "patchouli", "cedre-atlas", "lavande"],
    ifraCategoryFlags: ["Allergen labeling (citronellol, geraniol)"],
    defaultPercent: 5,
    volatility: 0.62,
    position: { tier: 1, slot: 9 },
    hexColor: "#C8A8B0",
  },
  {
    id: "muguet-hedione",
    name: "Muguet (Hedione)",
    commonName: "Lily of the Valley",
    family: "floral",
    role: "heart",
    cas: "24851-98-7",
    description:
      "Lily-of-the-valley does not give up an essential oil — every muguet in perfumery is a constructed accord built around hedione. Lifts and aerates the entire formula.",
    classicPairings: ["neroli-tunisia", "rose-de-mai", "iso-e-super", "florhydral"],
    ifraCategoryFlags: [],
    defaultPercent: 8,
    volatility: 0.65,
    position: { tier: 1, slot: 10 },
    hexColor: "#E8E1C8",
  },
  {
    id: "violette",
    name: "Violette",
    commonName: "Violet",
    family: "floral",
    role: "heart",
    cas: "32214-91-8",
    description:
      "Powdered, cosmetic, slightly metallic. The flower of memory — smells like a grandmother's purse and a Parma confectioner's window in equal measure. Carries iris beautifully.",
    classicPairings: ["iris-orris", "feuille-de-violette", "feve-tonka", "cassis"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.6,
    position: { tier: 1, slot: 11 },
    hexColor: "#C8B0D9",
  },

  {
    id: "sel-marin",
    name: "Sel Marin (Accord)",
    commonName: "Sea Salt Accord",
    family: "aquatic",
    role: "heart",
    cas: "14808-79-8",
    description:
      "A constructed accord — sodium chloride has no smell. Built from helional, dihydromyrcenol, and ambroxan to suggest the line where salt air meets warm skin.",
    classicPairings: ["ambroxan", "iso-e-super", "cedre-atlas", "helional"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.65,
    position: { tier: 1, slot: 12 },
    hexColor: "#B8C8D0",
  },

  {
    id: "poivre-noir",
    name: "Poivre Noir",
    commonName: "Black Pepper",
    family: "spice",
    role: "heart",
    cas: "8006-82-4",
    description:
      "Dry, biting, almost metallic at the start. Adds tension without warmth — closer to wasabi than to cinnamon in effect. Sits well in masculine florals.",
    classicPairings: ["rose-de-mai", "iso-e-super", "cedre-virginia", "cardamome"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.7,
    position: { tier: 1, slot: 13 },
    hexColor: "#7A4F30",
  },
  {
    id: "poivre-rose",
    name: "Poivre Rose",
    commonName: "Pink Pepper",
    family: "spice",
    role: "heart",
    cas: "91722-31-3",
    description:
      "Sweeter, brighter, more sparkling than black pepper. Almost gin-like at the top. The favored spice of the 2010s — overused but effective.",
    classicPairings: ["rose-de-mai", "pamplemousse-rose", "oud", "iris-orris"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.78,
    position: { tier: 1, slot: 14 },
    hexColor: "#C46878",
  },
  {
    id: "cardamome",
    name: "Cardamome (Guatemala)",
    commonName: "Cardamom",
    family: "spice",
    role: "heart",
    cas: "8000-66-6",
    description:
      "Eucalyptus-camphor on top, sweet milky base. The spice that makes rose readable as exotic without going to baklava. Pairs almost universally.",
    classicPairings: ["rose-damascena", "oud", "orange-douce", "santal-mysore"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.72,
    position: { tier: 1, slot: 15 },
    hexColor: "#B89868",
  },
  {
    id: "cannelle",
    name: "Cannelle (Ceylan)",
    commonName: "Cinnamon Bark",
    family: "spice",
    role: "heart",
    cas: "8015-91-6",
    description:
      "The whole stick, not the powder — drier, less candy. A small percent reads as oriental warmth; a large percent reads as Yankee Candle. Dose with fear.",
    classicPairings: ["vanille-bourbon", "orange-douce", "benjoin", "patchouli"],
    ifraCategoryFlags: ["Cinnamal sensitizer — Cat 4 limits 0.05% in EdT"],
    defaultPercent: 1,
    volatility: 0.6,
    position: { tier: 1, slot: 16 },
    hexColor: "#A8542A",
  },
  {
    id: "safran",
    name: "Safran (Iran)",
    commonName: "Saffron",
    family: "spice",
    role: "heart",
    cas: "8022-19-3",
    description:
      "Leather, hay, and a metallic-dry sweetness. Belongs to the same family as rose damascenone — they enhance each other. The spice of new Middle Eastern compositions.",
    classicPairings: ["rose-damascena", "oud", "cuir", "labdanum"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.55,
    position: { tier: 1, slot: 17 },
    hexColor: "#D9883A",
  },
  {
    id: "gingembre",
    name: "Gingembre Frais",
    commonName: "Fresh Ginger",
    family: "spice",
    role: "heart",
    cas: "8007-08-7",
    description:
      "Bright, lemony, slightly soapy. The CO2 extract is the only one worth using in fine fragrance; the steam-distilled is for soap. Modern, alive.",
    classicPairings: ["lime-persian", "pamplemousse-rose", "magnolia", "iso-e-super"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.78,
    position: { tier: 1, slot: 18 },
    hexColor: "#E8B868",
  },
  {
    id: "baies-de-genevrier",
    name: "Baies de Genévrier",
    commonName: "Juniper Berry",
    family: "spice",
    role: "heart",
    cas: "8002-68-4",
    description:
      "Pine-resinous, alpine, dry. The smell of a martini glass. Unusual in fine fragrance and instantly recognizable for it.",
    classicPairings: ["cypres", "galbanum", "cedre-atlas", "iso-e-super"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.74,
    position: { tier: 1, slot: 19 },
    hexColor: "#88A878",
  },

  {
    id: "cedre-virginia",
    name: "Cèdre Virginia",
    commonName: "Virginia Cedarwood",
    family: "wood",
    role: "heart",
    cas: "8000-27-9",
    description:
      "Pencil shavings, dry, slightly sweet. The most cooperative wood in the palette — sits under almost anything without claiming attention. The connective tissue of modern compositions.",
    classicPairings: ["iso-e-super", "iris-orris", "vetiver-haiti", "rose-de-mai"],
    ifraCategoryFlags: [],
    defaultPercent: 6,
    volatility: 0.4,
    position: { tier: 1, slot: 20 },
    hexColor: "#8B6F47",
  },
  {
    id: "cedre-atlas",
    name: "Cèdre Atlas",
    commonName: "Atlas Cedarwood",
    family: "wood",
    role: "heart",
    cas: "8023-85-6",
    description:
      "Drier and more amber than Virginia. The Moroccan cedar — sits at the boundary of wood and resin. A good choice when Virginia would feel too anonymous.",
    classicPairings: ["labdanum", "rose-damascena", "oud", "galbanum"],
    ifraCategoryFlags: [],
    defaultPercent: 5,
    volatility: 0.38,
    position: { tier: 1, slot: 21 },
    hexColor: "#7E5F3D",
  },
  {
    id: "cypres",
    name: "Cyprès (Crète)",
    commonName: "Cypress",
    family: "wood",
    role: "heart",
    cas: "8013-86-3",
    description:
      "Coniferous, dry, almost saline. The wood of churches and northern forests. Underused; sits beautifully with juniper and bergamot for an austere opening.",
    classicPairings: ["baies-de-genevrier", "bergamote-italian", "vetiver-haiti", "galbanum"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.55,
    position: { tier: 1, slot: 22 },
    hexColor: "#6E7E5A",
  },
  {
    id: "palissandre",
    name: "Palissandre",
    commonName: "Rosewood",
    family: "wood",
    role: "heart",
    cas: "8005-79-7",
    description:
      "Clean, slightly floral, nearly minty. Brazilian rosewood is ecologically restricted now; the fair substitute is reconstituted from linalool. Adds polish to a base.",
    classicPairings: ["santal-mysore", "rose-de-mai", "feve-tonka", "iris-orris"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.5,
    position: { tier: 1, slot: 23 },
    hexColor: "#A07D5C",
  },

  {
    id: "iso-e-super",
    name: "Iso E Super",
    commonName: "Iso E Super",
    family: "musk",
    role: "heart",
    cas: "54464-57-2",
    description:
      "A whispered cedar that smells like skin. Used at 5% it lifts everything around it; used at 50% it becomes Molecule 01. Disappears into other materials and makes them better.",
    classicPairings: ["rose-de-mai", "iris-orris", "patchouli", "ambroxan"],
    ifraCategoryFlags: [],
    defaultPercent: 12,
    volatility: 0.45,
    position: { tier: 1, slot: 24 },
    hexColor: "#C8B79A",
  },
  {
    id: "cashmeran",
    name: "Cashmeran",
    commonName: "Cashmeran",
    family: "musk",
    role: "heart",
    cas: "33704-61-9",
    description:
      "Velvet — there is no better word. Pine, musk, slightly fruity. Sits between wood and musk, lengthens drydown without weight. Modern luxury's favorite material.",
    classicPairings: ["ambroxan", "iris-orris", "rose-de-mai", "cedre-virginia"],
    ifraCategoryFlags: [],
    defaultPercent: 5,
    volatility: 0.32,
    position: { tier: 1, slot: 25 },
    hexColor: "#B8A890",
  },
  {
    id: "galaxolide",
    name: "Galaxolide",
    commonName: "Galaxolide",
    family: "musk",
    role: "heart",
    cas: "1222-05-5",
    description:
      "The clean white musk of fabric softeners — but used judiciously, the longest-lasting clean musk in fine fragrance. Cheap, ubiquitous, indispensable.",
    classicPairings: ["ambroxan", "iso-e-super", "magnolia", "helional"],
    ifraCategoryFlags: [],
    defaultPercent: 8,
    volatility: 0.25,
    position: { tier: 1, slot: 26 },
    hexColor: "#D8C8B0",
  },
  {
    id: "hedione-pure",
    name: "Hédione",
    commonName: "Hedione",
    family: "musk",
    role: "heart",
    cas: "24851-98-7",
    description:
      "A jasmine-related material that does not smell of jasmine alone — it makes other materials more themselves. The most-used molecule in fine perfumery for 50 years. A fragrance physicist's tool.",
    classicPairings: ["rose-de-mai", "jasmin-sambac", "iso-e-super", "magnolia"],
    ifraCategoryFlags: [],
    defaultPercent: 10,
    volatility: 0.55,
    position: { tier: 1, slot: 27 },
    hexColor: "#E0D4B8",
  },

  {
    id: "santal-mysore",
    name: "Santal Mysore",
    commonName: "Mysore Sandalwood",
    family: "wood",
    role: "base",
    cas: "8006-87-9",
    description:
      "The original creamy, milky, slightly urinous sandalwood. Indian export is restricted now — the closest substitute is Australian sandalwood blended with javanol. Honors the original at half the soul.",
    classicPairings: ["rose-de-mai", "ylang-ylang", "oud", "vanille-bourbon"],
    ifraCategoryFlags: [],
    defaultPercent: 6,
    volatility: 0.18,
    position: { tier: 2, slot: 0 },
    hexColor: "#C49968",
  },
  {
    id: "vetiver-haiti",
    name: "Vétiver (Haïti)",
    commonName: "Haitian Vetiver",
    family: "wood",
    role: "base",
    cas: "8016-96-4",
    description:
      "Wet earth, smoke, grapefruit peel — Haitian is the cleanest grade; Bourbon is denser and rooty. The base of every fougère worth wearing.",
    classicPairings: ["bergamote-italian", "rose-de-mai", "iso-e-super", "mousse-de-chêne"],
    ifraCategoryFlags: [],
    defaultPercent: 5,
    volatility: 0.2,
    position: { tier: 2, slot: 1 },
    hexColor: "#5C5530",
  },
  {
    id: "oud",
    name: "Oud (Agarwood)",
    commonName: "Oud",
    family: "wood",
    role: "base",
    cas: "8022-94-4",
    description:
      "The most polarizing note in modern perfumery. Animalic, leathery, medicinal — born from a fungal infection of the agarwood tree. Strange, ancient, expensive. Use with cardamom and rose for the classic Middle Eastern accord.",
    classicPairings: ["rose-damascena", "cardamome", "safran", "labdanum"],
    ifraCategoryFlags: [
      "Naturally complex — contains restricted constituents; consult IFRA Cat-by-Cat",
    ],
    defaultPercent: 3,
    volatility: 0.15,
    position: { tier: 2, slot: 2 },
    hexColor: "#4A2E1F",
  },
  {
    id: "bois-de-gaiac",
    name: "Bois de Gaïac",
    commonName: "Guaiac Wood",
    family: "wood",
    role: "base",
    cas: "8016-23-7",
    description:
      "Smoky, dry, slightly leathery. The smell of a campfire in a cathedral. Pairs strikingly with rose and oud; substitutes credibly for forbidden woods.",
    classicPairings: ["rose-damascena", "labdanum", "oud", "cuir"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.18,
    position: { tier: 2, slot: 3 },
    hexColor: "#5E3F28",
  },

  {
    id: "encens",
    name: "Encens (Somalie)",
    commonName: "Frankincense",
    family: "resin",
    role: "base",
    cas: "8050-07-5",
    description:
      "Lemon-pine on top, deep balsamic underneath. The smell of churches and tombs. Carries through long after softer materials have faded — a structural base.",
    classicPairings: ["myrrhe", "labdanum", "rose-de-mai", "cedre-atlas"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.22,
    position: { tier: 2, slot: 4 },
    hexColor: "#A8703D",
  },
  {
    id: "myrrhe",
    name: "Myrrhe",
    commonName: "Myrrh",
    family: "resin",
    role: "base",
    cas: "8016-37-3",
    description:
      "Bitter, medicinal, with a strange mushroom-truffle quality. Slightly leather. Less popular than frankincense and more interesting for it.",
    classicPairings: ["encens", "oud", "iris-orris", "patchouli"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.18,
    position: { tier: 2, slot: 5 },
    hexColor: "#7A4D2E",
  },
  {
    id: "labdanum",
    name: "Labdanum",
    commonName: "Labdanum",
    family: "resin",
    role: "base",
    cas: "8016-26-0",
    description:
      "The amber. The skin of every oriental composition — leather, honey, hay, slightly animalic. Replaces ambergris when ambergris is unavailable, which is always now.",
    classicPairings: ["benjoin", "vanille-bourbon", "rose-damascena", "patchouli"],
    ifraCategoryFlags: [],
    defaultPercent: 5,
    volatility: 0.15,
    position: { tier: 2, slot: 6 },
    hexColor: "#8B5A3C",
  },
  {
    id: "benjoin",
    name: "Benjoin (Siam)",
    commonName: "Benzoin",
    family: "resin",
    role: "base",
    cas: "9000-72-0",
    description:
      "Vanilla and balsamic, a softer sweetness than vanilla itself. The Siam grade is cleaner and less medicinal than Sumatran. The smell of warm wax.",
    classicPairings: ["vanille-bourbon", "feve-tonka", "cannelle", "labdanum"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.2,
    position: { tier: 2, slot: 7 },
    hexColor: "#B07840",
  },
  {
    id: "opoponax",
    name: "Opoponax",
    commonName: "Opoponax",
    family: "resin",
    role: "base",
    cas: "9000-78-6",
    description:
      'Sweet myrrh — softer, more honeyed, less medicinal. The "sweet myrrh" of antiquity. Sits beautifully under amber accords.',
    classicPairings: ["myrrhe", "labdanum", "benjoin", "rose-damascena"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.2,
    position: { tier: 2, slot: 8 },
    hexColor: "#A06B3A",
  },

  {
    id: "ambroxan",
    name: "Ambroxan",
    commonName: "Ambroxan",
    family: "musk",
    role: "base",
    cas: "6790-58-5",
    description:
      "The synthetic that replaced ambergris. Salt, skin, driftwood, warmth. The single most-used base material of the past 20 years. Used at 1% it haloes; at 10% it becomes the perfume.",
    classicPairings: ["iso-e-super", "cedre-atlas", "rose-de-mai", "pamplemousse-rose"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.25,
    position: { tier: 2, slot: 9 },
    hexColor: "#D9C49A",
  },
  {
    id: "habanolide",
    name: "Habanolide",
    commonName: "Habanolide",
    family: "musk",
    role: "base",
    cas: "111879-80-2",
    description:
      "A clean, slightly powdery macrocyclic musk. Less sweet than galaxolide, more interesting than ethyl brassylate. Reads expensive.",
    classicPairings: ["ambroxan", "iso-e-super", "iris-orris", "rose-de-mai"],
    ifraCategoryFlags: [],
    defaultPercent: 6,
    volatility: 0.22,
    position: { tier: 2, slot: 10 },
    hexColor: "#C8B898",
  },
  {
    id: "ethyl-brassylate",
    name: "Ethyl Brassylate",
    commonName: "Ethyl Brassylate",
    family: "musk",
    role: "base",
    cas: "105-95-3",
    description:
      "The cleanest-clean white musk. Almost transparent. The musk you reach for when nothing else should be reaching at all. The base of skin scents.",
    classicPairings: ["ambroxan", "iris-orris", "magnolia", "iso-e-super"],
    ifraCategoryFlags: [],
    defaultPercent: 8,
    volatility: 0.22,
    position: { tier: 2, slot: 11 },
    hexColor: "#E0D4BC",
  },
  {
    id: "norlimbanol",
    name: "Norlimbanol",
    commonName: "Norlimbanol",
    family: "musk",
    role: "base",
    cas: "70788-30-6",
    description:
      "Dry, hot, almost dusty wood-amber. Doesn't belong to any single family — sits between woody and ambery. Used at 0.5% it adds suntan-leather warmth; at 5% it becomes the desert.",
    classicPairings: ["cedre-atlas", "oud", "labdanum", "iso-e-super"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.18,
    position: { tier: 2, slot: 12 },
    hexColor: "#B8987A",
  },

  {
    id: "vanille-bourbon",
    name: "Vanille Bourbon",
    commonName: "Madagascar Vanilla",
    family: "gourmand",
    role: "base",
    cas: "8024-06-4",
    description:
      "The absolute, not the synthetic — three years of cure on the bean. Smoky, slightly tobacco, honeyed. Real vanilla never reads as cake.",
    classicPairings: ["feve-tonka", "ylang-ylang", "benjoin", "labdanum"],
    ifraCategoryFlags: [],
    defaultPercent: 4,
    volatility: 0.2,
    position: { tier: 2, slot: 13 },
    hexColor: "#C8985C",
  },
  {
    id: "feve-tonka",
    name: "Fève Tonka",
    commonName: "Tonka Bean",
    family: "gourmand",
    role: "base",
    cas: "8046-22-8",
    description:
      "Almond, hay, vanilla, tobacco — all at once. The hidden material in half the great gourmands. Use the absolute, not the coumarin isolate.",
    classicPairings: ["vanille-bourbon", "iris-orris", "lavande", "labdanum"],
    ifraCategoryFlags: ["Coumarin content — Cat-specific limits in oral care"],
    defaultPercent: 4,
    volatility: 0.22,
    position: { tier: 2, slot: 14 },
    hexColor: "#A88858",
  },
  {
    id: "coumarine",
    name: "Coumarine",
    commonName: "Coumarin",
    family: "gourmand",
    role: "base",
    cas: "91-64-5",
    description:
      "The synthetic isolate from tonka. Hay, almond, slightly bitter. The foundation of fougère. Used at 5% in Jicky in 1889 and the structure has barely changed.",
    classicPairings: ["feve-tonka", "lavande", "mousse-de-chêne", "bergamote-italian"],
    ifraCategoryFlags: ["Cat-specific limits in oral and leave-on"],
    defaultPercent: 3,
    volatility: 0.25,
    position: { tier: 2, slot: 15 },
    hexColor: "#C0A06A",
  },
  {
    id: "miel",
    name: "Miel (Absolu)",
    commonName: "Honey Absolute",
    family: "gourmand",
    role: "base",
    cas: "8028-66-8",
    description:
      "Sticky, animalic, slightly fecal at full strength. The bridge between gourmand and animalic. Use with rose for narcosis; with neroli for warmth.",
    classicPairings: ["rose-damascena", "tubéreuse", "labdanum", "civette"],
    ifraCategoryFlags: [],
    defaultPercent: 2,
    volatility: 0.22,
    position: { tier: 2, slot: 16 },
    hexColor: "#C68A2A",
  },
  {
    id: "praline",
    name: "Praliné (Accord)",
    commonName: "Praline Accord",
    family: "gourmand",
    role: "base",
    cas: "6485-40-1",
    description:
      "A constructed accord of caramel, hazelnut, and ethyl maltol. The signature of Angel; the reason the 1990s smelled like pastry. Use sparingly or commit fully.",
    classicPairings: ["vanille-bourbon", "patchouli", "feve-tonka", "mandarine-rouge"],
    ifraCategoryFlags: [],
    defaultPercent: 3,
    volatility: 0.2,
    position: { tier: 2, slot: 17 },
    hexColor: "#B07A3A",
  },

  {
    id: "civette-synth",
    name: "Civette (Synthétique)",
    commonName: "Civet Accord",
    family: "animalic",
    role: "base",
    cas: "542-46-1",
    description:
      "The synthetic substitute for the African civet — faecal, leathery, narcotic. Used at 0.05% it makes a floral indecent in the best way; at 0.5% it becomes a problem.",
    classicPairings: ["jasmin-grandiflorum", "rose-damascena", "labdanum", "oud"],
    ifraCategoryFlags: [],
    defaultPercent: 1,
    volatility: 0.18,
    position: { tier: 2, slot: 18 },
    hexColor: "#5C3E2E",
  },
  {
    id: "castoreum-synth",
    name: "Castoréum (Synthétique)",
    commonName: "Castoreum Accord",
    family: "animalic",
    role: "base",
    cas: "8023-83-4",
    description:
      "The synthetic substitute for beaver castoreum — leather, smoke, tar. The base of every classic chypre and most leather accords. Strange, ancient, indispensable.",
    classicPairings: ["cuir", "labdanum", "oud", "mousse-de-chêne"],
    ifraCategoryFlags: [],
    defaultPercent: 1,
    volatility: 0.15,
    position: { tier: 2, slot: 19 },
    hexColor: "#4A2E1A",
  },
];

export const COMPOUNDS_BY_ID: Record<string, Compound> = Object.fromEntries(
  COMPOUNDS.map((c) => [c.id, c]),
);

export const compoundById = (id: string): Compound | undefined => COMPOUNDS_BY_ID[id];

export const compoundsByFamily = (family: Family): Compound[] =>
  COMPOUNDS.filter((c) => c.family === family);

export const compoundsByRole = (role: Role): Compound[] => COMPOUNDS.filter((c) => c.role === role);

export const compoundsByTier = (tier: 0 | 1 | 2): Compound[] =>
  COMPOUNDS.filter((c) => c.position.tier === tier).sort(
    (a, b) => a.position.slot - b.position.slot,
  );

export const PALETTE_SUMMARY = COMPOUNDS.map((c) => ({
  id: c.id,
  name: c.name,
  family: FAMILIES[c.family].label,
  role: c.role,
}));
