/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefRefRouteImport } from './routes/brief.$ref'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBriefRouteImport } from './routes/api/brief'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRefRoute = BriefRefRouteImport.update({
  id: '/brief/$ref',
  path: '/brief/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefRoute = ApiBriefRouteImport.update({
  id: '/api/brief',
  path: '/api/brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/$ref': typeof BriefRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/$ref': typeof BriefRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/$ref': typeof BriefRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library' | '/api/brief' | '/api/chat' | '/brief/$ref'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/api/brief' | '/api/chat' | '/brief/$ref'
  id: '__root__' | '/' | '/library' | '/api/brief' | '/api/chat' | '/brief/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  ApiBriefRoute: typeof ApiBriefRoute
  ApiChatRoute: typeof ApiChatRoute
  BriefRefRoute: typeof BriefRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$ref': {
      id: '/brief/$ref'
      path: '/brief/$ref'
      fullPath: '/brief/$ref'
      preLoaderRoute: typeof BriefRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief': {
      id: '/api/brief'
      path: '/api/brief'
      fullPath: '/api/brief'
      preLoaderRoute: typeof ApiBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  ApiBriefRoute: ApiBriefRoute,
  ApiChatRoute: ApiChatRoute,
  BriefRefRoute: BriefRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
